---

- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - python-dev
      - python-setuptools
      - python-virtualenv
      - git

- name: create a virtualenv to hold the app
  shell: virtualenv {{ virtualenv_dir }}

- name: Clone the repo
  git:
    repo: "{{ git_repo }}"
    version: "{{ branch }}"
    dest: "{{ biostar_dir }}"

- name: recursive file permissions
  sudo: true
  shell: chmod -R 744 {{ virtualenv_dir }}

- name: Copy env file
  template:
    src: ./files/biostar/conf/production.env
    dest: "{{ biostar_dir }}/conf/production.env"

- name: delete existing base settings
  file: path="{{ biostar_dir }}"/biostar/settings/base.py state=absent

- name: Copy the settings file
  template:
    src: ./files/biostar/settings/base.py
    dest: "{{ biostar_dir }}/biostar/settings/base.py"

- name: Copy logger file
  template:
    src: ./files/biostar/settings/logger_production.py
    dest: "{{ biostar_dir }}/biostar/settings/logger_production.py" 

- name: install requirements inside virtualenv
  pip: requirements="{{ requirement_dir }}" virtualenv={{ virtualenv_dir }}

- name: Copy cron-index
  template:
    src: ./files/biostar/cron-index.sh
    dest: "{{ biostar_dir }}/cron-index.sh"
    mode: 777

- name: Copy run-biostar
  template:
    src: ./files/biostar/run-biostar.sh
    dest: "{{ biostar_dir }}/run-biostar.sh"
    mode: 777

- name: Run biostar
  shell: "{{ biostar_dir }}/run-biostar.sh"
  sudo: yes

