---

- name: Launch an Amazon EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Load all variables
      include_vars: variables.yml
    - include: tasks/ec2.yml

- name: Set up docker on instance
  hosts: biostarhosts
  user: ubuntu
  gather_facts: False
  tasks:
    - name: Load all variables
      include_vars: variables.yml
    - include: tasks/docker.yml
    - include: tasks/postgresql.yml

- name: why
  hosts: biostarhosts
  user: ubuntu
  gather_facts: False
  tasks:
    - include: tasks/dockerip.yml
    - include: tasks/biostar.yml




