---

- name: Launch an Amazon EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Load all variables
      include_vars: variables.yml
    - include: tasks/ec2.yml

- name: Start the Biostar process on Amazon EC2 instance
  hosts: biostarhosts
  user: ubuntu
  gather_facts: False
  tasks:
    - name: Load all variables
      include_vars: variables.yml
    - name: Start of docker installation
      include: tasks/docker.yml
    - name: Setting up Postgresql server
      include: tasks/postgresql.yml
    - name: Setting up biostar-central
      include: tasks/biostar.yml