---

- name: Biostar Set Up on Vagrant
  hosts: all
  gather_facts: false
  tasks:
    - name: Include variables
      include_vars: variables.yml
    - name: Set up postgres
      include: tasks/postgres.yml
    - name: Set up biostar virtualenv
      include: tasks/biostar.yml