---

- name: Ensure Docker server is running
  service:
    name: docker
    state: started
  sudo: True

- name: Run the PostgreSQL container
  command: docker run --name post -e POSTGRES_USER="{{ postgresql_username }}" -e POSTGRES_PASSWORD="{{ postgresql_password }}" -d postgres
  sudo: True

